# Data Cleaning Workflow

In [1]:
import pandas as pd

df = pd.read_csv("../data/climate_food_security_FINAL.csv")

df.head()

,country,iso_code,income_group,year,rice_yield,temperature,rainfall,fertilizer,gdp_per_capita,disaster_events,flood_events,drought_events,temperature_change,rainfall_change_percent,disaster_risk_score,climate_risk_level
0,Afghanistan,AFG,Low income,2001,2.0000,10.47,327,2.394898,277.118051,5.0,0.0,0.0,0.0,0.0,5.0,Medium
1,Algeria,DZA,Upper middle income,2001,1.2371,18.99,89,13.886325,3610.006056,1.0,1.0,0.0,0.0,0.0,2.5,Medium
2,Azerbaijan,AZE,Upper middle income,2001,4.8495,12.09,447,6.482541,1640.936645,0.0,0.0,0.0,0.0,0.0,0.0,Low
3,Bangladesh,BGD,Lower middle income,2001,3.4470,25.20,2666,174.590269,641.288923,7.0,2.0,0.0,0.0,0.0,10.0,High
4,Belize,BLZ,Upper middle income,2001,3.0137,25.11,1705,72.307692,5764.990555,2.0,0.0,0.0,0.0,0.0,2.0,Low

In [2]:
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1574 entries, 0 to 1573
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  1574 non-null   object
 1   iso_code                 1574 non-null   object
 2   income_group             1574 non-null   object
 3   year                     1574 non-null   int64
 4   rice_yield               1574 non-null   float64
 5   temperature              1574 non-null   float64
 6   rainfall                 1574 non-null   int64
 7   fertilizer               1574 non-null   float64
 8   gdp_per_capita           1574 non-null   float64
 9   disaster_events          1574 non-null   float64
 10  flood_events             1574 non-null   float64
 11  drought_events           1574 non-null   float64
 12  temperature_change       1574 non-null   float64
 13  rainfall_change_percent  1574 non-null   float64
 14  disaster_risk_score      1574 non-null   float64
 15  climate_risk_level       1574 non-null   object
dtypes: float64(10), int64(2), object(4)
memory usage: 196.9+ KB

country                    0
iso_code                   0
income_group               0
year                       0
rice_yield                 0
temperature                0
rainfall                   0
fertilizer                 0
gdp_per_capita             0
disaster_events            0
flood_events               0
drought_events             0
temperature_change         0
rainfall_change_percent    0
disaster_risk_score        0
climate_risk_level         0
dtype: int64

In [3]:
df.describe()

,year,rice_yield,temperature,rainfall,fertilizer,gdp_per_capita,disaster_events,flood_events,drought_events,temperature_change,rainfall_change_percent,disaster_risk_score
count,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000,1574.000000
mean,2011.571792,3.389334,22.329441,1336.268742,105.171988,3017.672502,3.178526,1.442186,0.141042,0.022119,-0.000740,5.553367
std,6.309530,1.705076,5.599280,833.343973,233.886894,2586.589422,4.743707,2.292396,0.364238,0.406824,0.051665,8.067678
min,2001.000000,0.285700,4.256000,89.000000,0.000000,250.878933,0.000000,0.000000,0.000000,-2.270000,-1.178451,0.000000
25%,2006.000000,2.104175,20.610000,645.000000,8.851127,958.858759,1.000000,0.000000,0.000000,-0.180000,0.000000,1.000000
50%,2012.000000,3.294250,24.135000,1187.000000,37.247995,2014.517261,2.000000,1.000000,0.000000,0.000000,0.000000,3.500000
75%,2017.000000,4.335600,26.117500,1976.000000,117.385774,4550.956144,4.000000,2.000000,0.000000,0.226750,0.000000,7.000000
max,2022.000000,11.383600,29.610000,3240.000000,2299.420938,11830.598370,43.000000,25.000000,3.000000,2.143000,1.192504,68.500000